[build]
builder = "nixpacks"
buildCommand = "npm ci && npx prisma generate && npx prisma migrate deploy && npm run build"

[deploy]
startCommand = "npm run start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production.deploy]
healthcheckPath = "/"
healthcheckTimeout = 30
